baseURL = "https://tonyxu.io/"
footnoteReturnLinkContents = "↩"
title = "Tony Xu"
theme = "hyde"
disqusShortname = "tonyxu-io"
googleAnalytics     = "UA-577792-7"
pygmentsCodeFences = true
pygmentsStyle = "tango"
defaultContentLanguage = "en"

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[languages]
  [languages.en]
    LanguageName = "English"

  [languages.zh]
    LanguageName = "简体中文"
    title = "Tony Xu 徐毅涵"
    weight = 2
    copyright = "© 2018 徐毅涵"
    [languages.zh.params]
      description = "LinkedIn领英软件工程师，热爱编程和生活"
    [[languages.zh.menu.main]]
    name                   = "主页"
    weight                 = 11
    identifier             = "home"
    url                    = "/"
    pre                    = "<span class=\"icon-home menu-icon\"></span>"

    [[languages.zh.menu.main]]
    name                   = "关于"
    weight                 = 12
    identifier             = "about"
    url                    = "/about"
    pre                    = "<span class=\"icon-user menu-icon\"></span>"

    [[languages.zh.menu.main]]
    name                   = "文章"
    weight                 = 21
    identifier             = "posts"
    url                    = "/posts"
    pre                    = "<span class=\"icon-pencil menu-icon\"></span>"

    [[languages.zh.menu.main]]
    name                   = "项目"
    weight                 = 31
    identifier             = "projects"
    url                    = "/projects"
    pre                    = "<span class=\"icon-plug menu-icon\"></span>"

    [[languages.zh.menu.main]]
    name                   = "资料"
    weight                 = 41
    identifier             = "profile"
    url                    = "https://linkedin.com/in/tonyxu93?locale=zh_CN"
    pre                    = "<span class=\"icon-linkedin-square menu-icon\"></span>"

[params]
  AuthorName = "Tony Xu"
  GitHubUser = "tonyxu-io"
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"
  themeColor = "theme-base-10"
  description            = "A LinkedIn software engineer, loves to build, ship, launch."
  postsDir = "posts"
  cover = "favicons/favicon-200.png"
  copyright = "© 2018 Tony Xu"

[permalinks]
  posts = "/posts/:year/:slug/"

[menu]

    [[menu.main]]
    name                   = "Home"
    weight                 = 10
    identifier             = "home"
    url                    = "/"
    pre                    = "<span class=\"icon-home menu-icon\"></span>"

    [[menu.main]]
    name                   = "About"
    weight                 = 12
    identifier             = "about"
    url                    = "/about"
    pre                    = "<span class=\"icon-user menu-icon\"></span>"

    [[menu.main]]
    name                   = "Posts"
    weight                 = 20
    identifier             = "posts"
    url                    = "/posts"
    pre                    = "<span class=\"icon-pencil menu-icon\"></span>"

    [[menu.main]]
    name                   = "Projects"
    weight                 = 30
    identifier             = "projects"
    url                    = "/projects"
    pre                    = "<span class=\"icon-plug menu-icon\"></span>"

    [[menu.main]]
    name                   = "Profile"
    weight                 = 40
    identifier             = "profile"
    url                    = "https://linkedin.com/in/tonyxu93"
    pre                    = "<span class=\"icon-linkedin-square menu-icon\"></span>"