baseURL = "https://tonyxu.io/"
footnoteReturnLinkContents = "↩"
title = "Tony Xu 徐毅涵"
theme = "hyde"
disqusShortname = "tonyxu-io"
googleAnalytics     = "UA-577792-7"

[params]
  AuthorName = "Tony Xu"
  GitHubUser = "tonyxu-io"
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"
  themeColor = "theme-base-10"
  description            = "A LinkedIn engineer, loves to build, ship, and launch."
  postsDir = "posts"
  cover = "favicons/favicon-200.png"

[permalinks]
  posts = "/posts/:title/"

[menu]

    [[menu.main]]
    name                   = "Home"
    weight                 = -160
    identifier             = "home"
    url                    = "/"
    pre                    = "<i class='fas fa-fw fa-home menu-icon'></i>"

    [[menu.main]]
    name                   = "Posts"
    weight                 = -150
    identifier             = "posts"
    url                    = "/posts"
    pre                    = "<i class='fas fa-fw fa-pen-nib menu-icon'></i>"

    [[menu.main]]
    name                   = "Projects"
    weight                 = -140
    identifier             = "projects"
    url                    = "/projects"
    pre                    = "<i class='fas fa-fw fa-plug menu-icon'></i>"

    [[menu.main]]
    name                   = 'Profile'
    weight                 = -130
    identifier             = "profile"
    url                    = "https://linkedin.com/in/tonyxu93"
    pre                    = "<i class='fab fa-fw fa-linkedin menu-icon'></i>"

    [[menu.main]]
    name                   = 'Email'
    weight                 = -120
    identifier             = "email"
    url                    = "mailto:me@tonyxu.io"
    pre                    = "<i class='fas fa-fw fa-envelope menu-icon'></i>"