baseURL = "/"
footnoteReturnLinkContents = "↩"
title = "Tony Xu 徐毅涵"
theme = "hyde"
disqusShortname = "tonyxu-io"

[params]
  AuthorName = "Tony Xu"
  GitHubUser = "tonyxu-io"
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"
  themeColor = "theme-base-10"
  googleAnalytics     = "UA-577792-7"
  description            = "A LinkedIn engineer, loves to build, ship, and launch."
  postsDir = "posts"

[permalinks]
  posts = "/posts/:title/"

[menu]

    [[menu.main]]
    name                   = "Posts"
    weight                 = -150
    identifier             = "posts"
    url                    = "/posts"

    [[menu.main]]
    name                   = "Projects"
    weight                 = -140
    identifier             = "projects"
    url                    = "/projects"

    [[menu.main]]
    name                   = 'Profile'
    weight                 = -130
    identifier             = "profile"
    url                    = "https://linkedin.com/in/tonyxu93"

    [[menu.main]]
    name                   = 'Email'
    weight                 = -120
    identifier             = "email"
    url                    = "mailto:me@tonyxu.io"