baseURL = "https://tonyxu.io/" # Controls base URL
languageCode = "en-US" # Controls html lang attribute
title = "Bulma for Hugo" # Homepage title and page title suffix
paginate = 20 # Number of posts to show before paginating
theme = "bulma" # to use as default theme

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "UA-577792-7" # Optional, add tracking Id for analytics
disqusShortname = "tonyxu-io" # Optional, add Disqus shortname for comments
# SectionPagesMenu = "main" # Enable menu system for lazy bloggers

defaultContentLanguage = "en"

pygmentsCodeFences = true
pygmentsStyle = "tango"

hasCJKLanguage = true

[params]
  theme_variant = "" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  images = ["/images/og-image.png","/images/square-logo.webp"] # Suggested, controls default OpenGraph images controls author name display on meta tag
  github  = "tonyxu-io" # Optional, to display link to github account in menu bar
  linkedin = "tonyxu93" # Optional, to display link to twitter account in menu bar
  logo = "/images/square-logo.webp"

[blackfriday]
  extensions = ["hardLineBreak"]
  hrefTargetBlank = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Tony Xu Blog"
    weight = 1
    [languages.en.params]
      linkedin = "tonyxu93"
      author = "Tony Xu"
      IamAuthor = "I am Tony Xu"
      description = "I'm a software engineer. I love to build cool things with latest technologies and share my learnings from them."
      copyright = "© 2018-2019 Tony Xu"


  [languages.zh]
    languageName = "中文"
    title = "Tony Xu 博客"
    weight = 2
    [languages.zh.params]
      linkedin = "tonyxu93"
      author = "Tony Xu"
      IamAuthor = "我是 Tony Xu"
      description = "我是一名软件工程师，热爱尝试和分享最新科技"
      copyright = "© 2018-2019 Tony Xu 徐毅涵"

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]