baseURL = "/"
footnoteReturnLinkContents = "↩"
title = "Tony Xu 徐毅涵"
theme = "hyde"
disqusShortname = "tonyxu-io"

[params]
  AuthorName = "Tony Xu"
  GitHubUser = "tonyxu-io"
  SidebarRecentLimit = 5
  Subtitle = "Hugo is Absurdly Fast!"
  themeColor = "theme-base-10"
  googleAnalytics     = "UA-577792-7"
  description            = "A LinkedIn engineer, loves to build, ship, and launch."

[permalinks]
  post = "posts/:title/"

[menu]

    [[menu.main]]
    name                   = "Projects"
    weight                 = -110
    identifier             = "projects"
    url                    = "/pages/projects"

    [[menu.main]]
    name                   = "Profile"
    weight                 = -100
    identifier             = "profile"
    url                    = "https://linkedin.com/in/tonyxu93"